version: '3'
services:
  backend:
    build: .  # Đường dẫn đến thư mục Flask
    ports:
      - "5000:5000"  # Map port từ container ra ngoài
    networks:
      - app-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: student_db1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
