"""Add ON DELETE CASCADE to student_id in StudentSubject

Revision ID: 29ff79f43332
Revises: 520bf09d80ab
Create Date: 2024-11-03 21:58:24.210009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ff79f43332'
down_revision = '520bf09d80ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject', schema=None) as batch_op:
        batch_op.drop_constraint('student_subject_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_register', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_subject_student_id_fkey', 'student_register', ['student_id'], ['id'])

    # ### end Alembic commands ###
