"""delete course field

Revision ID: 6ce264b6b175
Revises: 29ff79f43332
Create Date: 2024-11-03 22:06:49.963596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce264b6b175'
down_revision = '29ff79f43332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_register', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
